version: '3.8'

services:
  env-loader:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - WORKDIR
    volumes:
      - env:$WORKDIR
      - ./test/fixture/volumes/secret:$WORKDIR/secret
      - ./test/fixture/volumes/ssm:$WORKDIR/ssm
  validator:
    depends_on: [ env-loader ]
    build:
      dockerfile: Dockerfile
      context: ./test
    environment:
      - WORKDIR
    volumes:
      - env:$WORKDIR
      - ./test/expectation:/expectation
volumes:
  env:
    driver: local
