version: '3.8'

services:
  env-loader:
    build:
      dockerfile: Dockerfile
      context: .
    volumes:
      - ./test/fixture/volumes:/etc
      - shared-tmpfs:/etc/env
  validator:
    depends_on: [ env-loader ]
    build:
      dockerfile: Dockerfile
      context: ./test
    volumes:
      - ./test/fixture/volumes:/etc
      - ./test/expectation:/expectation
      - shared-tmpfs:/etc/env

volumes:
  shared-tmpfs:
    driver: local
    driver_opts:
      type: "tmpfs"
      device: "tmpfs"
      o: "size=256m,uid=1000"
